# runtime: python
# env: flex
# entrypoint: gunicorn -b :$PORT quiz:app

# # service: quizapp

# runtime_config:
#     python_version: 3

# env_variables:
#     CLOUD_STORAGE_BUCKET: $GCLOUD_BUCKET
runtime: python39 # or another supported version

# instance_class: F2

# env_variables:
#   BUCKET_NAME: "quiz-app-hello-quiz_app"

# handlers:
# - url: /.*
#   secure: always
#   redirect_http_response_code: 301
#   script: auto